runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

service: restapibooks-flex

runtime_config:
  python_version: 3

handlers:
- url: /.*
  script: main.app

env_variables:
    SQLALCHEMY_DATABASE_URI: >-
        mysql+pymysql://root:root@/bookshelf?unix_socket=/cloudsql/wave18-peringer:europe-west1:library1